name: Deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install
        cd backend && npm install
        
    - name: Build frontend
      run: npm run build
      
    - name: Deploy backend
      run: |
        cd backend
        if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
          npm run deploy-aws
          echo "Backend deployed to AWS"
        else
          npm run deploy
          echo "Mock deployment completed - no AWS credentials configured"
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Deploy frontend to S3
      run: |
        if [ -n "${{ secrets.S3_BUCKET }}" ]; then
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }} --delete
          echo "Frontend deployed to S3"
        else
          echo "S3_BUCKET not configured - skipping S3 deployment"
          echo "Build artifacts available in dist/ folder"
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}